Start compiling scala-library 2.13.3 instead of 2.12.12
To avoid the following compile errors in 2.12.12
```
home/runner/work/scalameta/scalameta/target/scala-library/scala-2.12.12/src/library/scala/collection/immutable/TreeMap.scala:333: error: type arguments [_] do not conform to class SortedMapFactory's type parameter bounds [CC[A, B] <: scala.collection.SortedMap[A,B] with scala.collection.SortedMapLike[A,B,CC[A,B]]]
      case cbf: SortedMapFactory[_]#SortedMapCanBuildFrom[_,_] => {
                ^
/home/runner/work/scalameta/scalameta/target/scala-library/scala-2.12.12/src/library/scala/collection/immutable/TreeSet.scala:210: error: type arguments [_] do not conform to class SortedSetFactory's type parameter bounds [CC[A] <: scala.collection.SortedSet[A] with scala.collection.SortedSetLike[A,CC[A]]]
      case cbf: SortedSetFactory[_]#SortedSetCanBuildFrom[_] => {
                ^
two errors found
```

There is no reason we need to compile the sources of 2.12.12.