temporarily downgrade our coverage of the test corpus
Previously: http://drone.geirsson.com:8001/scalameta/paradise/231
ConvertException: unexpected result: expected = Pat, actual = Pat.Type.Apply: 2
ConvertException: PackageDef: 2
ConvertException: unexpected result: expected = Pat.Type, actual = Type.Function: 3
ConvertException: Ident: 4
ConvertException: Bind: 5
ConvertException: ModuleDef: 11
ConvertException: unexpected result: expected = Pat.Type, actual = Type.Project: 12
UnreachableError: this code path should've been unreachable: 19
ConvertException: unexpected error (scroll down the stacktrace to see the cause):: 66
TestFailedException: parse error: 1433
Success: 25950

Now: http://drone.geirsson.com:8001/scalameta/scalameta/135
ConvertException: unexpected result: expected = Pat, actual = Pat.Type.Apply: 2
ConvertException: PackageDef: 2
ConvertException: unexpected result: expected = Pat.Type, actual = Type.Function: 3
ConvertException: Ident: 4
ConvertException: Bind: 5
ConvertException: ModuleDef: 11
ConvertException: unexpected result: expected = Pat.Type, actual = Type.Project: 12
UnreachableError: this code path should've been unreachable: 19
ConvertException: unexpected error (scroll down the stacktrace to see the cause):: 62
TestFailedException: parse error: 2637
Success: 24750

Looks like we’re getting almost 1.5k new parse errors by migrating
the converter from scalameta/paradise to scalameta/scalameta.