Downgrade sbt-bintray.
While publishing to bintray I got errors
```
[error] (scalahostSbt/*:bintrayEnsureBintrayPackageExists)
                       java.lang.NoSuchMethodError:
                       org.json4s.Formats.emptyValueStrategy()Lorg/json4s/prefs/EmptyValueStrategy;
```
Then when I downgraded to 0.3.0 I got a new error

```
[error]
setting(ScopedKey(Scope(Select(ProjectRef(file:/Users/ollie/dev/scalameta/,scalahostSbt)),Global,Global,Global),bintrayRelease))
at LinePosition(/Users/ollie/dev/scalameta/build.sbt,555) referenced
from
ScopedKey(Scope(Select(ProjectRef(file:/Users/ollie/dev/scalameta/,scalahostSbt)),Global,Global,Global),bintrayRelease)
```

The task bintrayRelease shouldn't be called if publishTo is set to
something custom.